export const ELEMENT_NODE: 1;
export const TEXT_NODE: 3;
export function isElement(node: Node): boolean;
export function isText(node: Node): boolean;
export function isVoid(node: Node): boolean;
export function isPara(node: Node): boolean;
export function isLi(node: Node): boolean;
export function isList(node: Node): boolean;
export function isTable(node: Node): boolean;
export function isInline(node: Node): boolean;
export function isEditable(node: Node): boolean;
export function isAnchor(node: Node): boolean;
export function isImage(node: Node): boolean;
export function closest(node: Node, predicate: (node: Node) => boolean, stopAt?: Node): Node | null;
export function closestPara(node: Node, editable?: Node): Node | null;
export function ancestors(node: Node, stopAt?: Node): Node[];
export function children(node: Node): Node[];
export function prevElement(node: Node): Element | null;
export function nextElement(node: Node): Element | null;
export function createElement(tag: string, attrs?: Record<string, string>, childNodes?: Array<Node | string>): HTMLElement;
export function remove(node: Node): void;
export function unwrap(node: Node): void;
export function wrap(node: Node, wrapper: HTMLElement): HTMLElement;
export function insertAfter(newNode: Node, refNode: Node): void;
export function nodeValue(node: Node): string;
export function isEmpty(node: Node): boolean;
export function outerHtml(el: Element): string;
export function placeCaret(el: HTMLElement): void;
export function isInsideEditable(node: Node): boolean;
export function on(target: EventTarget, type: string, handler: EventListener, options?: AddEventListenerOptions): () => void;
export function trapFocus(container: HTMLElement, onEscape: () => void): () => void;
export function makeDraggable(handle: HTMLElement, box: HTMLElement): () => void;
